//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface Coordinate {
    latitude: number;
    longitude: number;
}