name: publish packages

on:
  push:
    # tags:
    #   - "v*.*.*" # publish only when you push a version tag (e.g. v1.0.0)
    branches:
      - main # or the branch you want to trigger the publish from

jobs:
  publish-typescript:
    name: Build and Publish TypeScript Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"

      - name: Restore & Build DTO generator
        run: |
          dotnet restore ./simpledispatch-shared-models.csproj
          dotnet build ./simpledispatch-shared-models.csproj

      - name: Generate TypeScript DTOs
        run: dotnet run --project ./simpledispatch-shared-models.csproj

      - name: Install TypeScript
        run: npm install typescript

      - name: Compile TypeScript
        run: npx tsc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-nuget:
    name: Build and Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ./simpledispatch-shared-models.csproj

      - name: Build project
        run: dotnet build ./simpledispatch-shared-models.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack ./simpledispatch-shared-models.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
